server:
  port: 8083

spring:
  application:
    name: spring-boot-item-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: item-service
            uri: lb://SPRING-BOOT-ITEM-SERVICE
            predicates:
              - Path=/api/v1/items/**
          - id: customer-service
            uri: lb://SPRINGBOOT-CUSTOMER-SERVICES
            predicates:
              - Path=/api/v1/customer/**


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

