server:
  port: 8084

spring:
  application:
    name: spring-boot-config-server
  profiles:
    active: native

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true